// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC61sKBJ8LEb9bIZrqBKDywfsfjVtTakAY',
    appId: '1:617140538662:web:206f4513983c65079245e7',
    messagingSenderId: '617140538662',
    projectId: 'calculo-trivial-app-646bb',
    authDomain: 'calculo-trivial-app-646bb.firebaseapp.com',
    storageBucket: 'calculo-trivial-app-646bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqfXxGbwJ5XB7rwSzq9mrbzewm0k3vjbc',
    appId: '1:617140538662:android:665a235fb59046509245e7',
    messagingSenderId: '617140538662',
    projectId: 'calculo-trivial-app-646bb',
    storageBucket: 'calculo-trivial-app-646bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0ulM7ZUBGnenKyBES8gR26TpGpMn16h4',
    appId: '1:617140538662:ios:621fffcd244698be9245e7',
    messagingSenderId: '617140538662',
    projectId: 'calculo-trivial-app-646bb',
    storageBucket: 'calculo-trivial-app-646bb.firebasestorage.app',
    iosBundleId: 'com.example.calcquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0ulM7ZUBGnenKyBES8gR26TpGpMn16h4',
    appId: '1:617140538662:ios:621fffcd244698be9245e7',
    messagingSenderId: '617140538662',
    projectId: 'calculo-trivial-app-646bb',
    storageBucket: 'calculo-trivial-app-646bb.firebasestorage.app',
    iosBundleId: 'com.example.calcquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC61sKBJ8LEb9bIZrqBKDywfsfjVtTakAY',
    appId: '1:617140538662:web:09d0c2c0fa5003a09245e7',
    messagingSenderId: '617140538662',
    projectId: 'calculo-trivial-app-646bb',
    authDomain: 'calculo-trivial-app-646bb.firebaseapp.com',
    storageBucket: 'calculo-trivial-app-646bb.firebasestorage.app',
  );
}
